### PR TITLE
Add rocket and mako

### PR DESCRIPTION
**Pull request by apcamargo**
Hi @sjmgarnier 

I started working in this PR to add `rocket` and `mako` to your package. I still need to add the tests before it's finished.

I couldn't find a script to generate a new `viridis-scales.png` in the same style as yours. Is it available somewhere?

Thanks!

### CODE REVIEW

**Comment by sjmgarnier** [comment]
That's a question for @noamross. I believe he created that figure in the first place.

**Comment by noamross** [comment]
The code to generate that figure is in the main viridis package vignette, here: https://github.com/sjmgarnier/viridis/blob/master/vignettes/intro-to-viridis.Rmd#L98-L103

**Comment by apcamargo** [comment]
Thanks @noamross !

@sjmgarnier I think the PR is complete. What do you think of it?

**Comment by sjmgarnier** [comment]
@apcamargo Busy week. I'll look at it this weekend if I can.

**Comment by apcamargo** [comment]
@sjmgarnier Thank for for the merge!

Do you think I should submit a PR to add these colormaps to the `viridis` package too?

**Comment by sjmgarnier** [comment]
@apcamargo Yes, go ahead.

**Pull request merged**
